### ISSUE TITLE
Collect Twitter tweets

### ISSUE THREAD

**Issue by Darkless012** [gis4dis/poster#1]
<a href="https://github.com/jirik"><img src="https://avatars0.githubusercontent.com/u/2271850?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jirik](https://github.com/jirik)**
_Friday Oct 13, 2017 at 11:28 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/gis4dis/poster_obsolete/issues/3_

----

We are interested in tweets from South Moravia region starting July 2017.

Processing ideas
Keywords
- sucho
- houby

**Comment by jirik** [comment]
Closing. Karst cancelled it because there is not enough sufficient tweets about such keywords.
