### ISSUE TITLE
TImeseries - Timeslot param

### ISSUE THREAD

**Issue by LudvikAdamec** [gis4dis/poster#142]

**Comment by jirik** [comment]
@LudvikAdamec Please describe new API endpoint and parameters related to timeslots (just edit v2, no need to create v3):
https://github.com/gis4dis/poster/wiki/Interface-between-MC-client-&-MC-server-v2

**Comment by jirik** [comment]
Add time slots to admin
- TimeSlots class administration
- add time_slots parameter to all observations views (list view, object view), enable to filter by time slot
