### ISSUE TITLE
Property_anomaly_percentiles empty

### ISSUE THREAD

**Issue by LudvikAdamec** [gis4dis/poster#170]
In get_timeseries is in property_anomaly_percentiles returned empty [ ]

**Comment by SLeitgeb** [comment]
What time extent / observation input / request? It's intended to return `{}` for anomaly and value percentiles when there are no valid observations:
https://github.com/gis4dis/poster/blob/4c2ac9acc6a3b8bf2f3af79e5a8ef24ce1e1289d/apps/ad/anomaly_detection.py#L78-L85
If this is not desirable, what should the output be?
