### ISSUE TITLE
time_slots endpoint does not respect order of time slots

### ISSUE THREAD

**Issue by jirik** [gis4dis/poster#176]
Request `/api/v2/time_slots/?topic=drought&format=json` returns different order of timeslots than order defined in settings.py:
```
[{"name_id":"1_hour_slot","name":"1_hour_slot"},{"name_id":"24_hour_slot","name":"24_hour_slot"},{"name_id":"30_days_daily","name":"30_days_daily"}]
```
vs.

https://github.com/gis4dis/poster/blob/c6d2b5cae8ad95d60e9a9a53a32d661ed37ef5db/apps/mc/settings.py#L59

**Comment by LudvikAdamec** [comment]
fix in https://github.com/gis4dis/poster/commit/b3b9befba43fc03ce2de0cd1c2e4ed59d164afe3
