### ISSUE TITLE
Jupyter: plot does not respect selected property

### ISSUE THREAD

**Issue by jirik** [gis4dis/poster#179]
air temperature and precipitation have same plot

![image](https://user-images.githubusercontent.com/2271850/61768884-f3741600-ade8-11e9-9928-d73a1f744317.png)

![image](https://user-images.githubusercontent.com/2271850/61768917-0e468a80-ade9-11e9-9a2f-31d7f800e491.png)

**Comment by SLeitgeb** [comment]
Which commit is that?
