### ISSUE TITLE
Missing watercourse stations

### ISSUE THREAD

**Issue by LudvikAdamec** [gis4dis/poster#29]
In file stanice_tok.csv is missing stations with ID: 036, 047, 054, 061, 112, 121, 122, 123, 132.

**Comment by jirik** [comment]
I've updated `stanice_tok.csv` with values from @stampachradim 
https://drive.google.com/file/d/15goHaIlGoxl58u5Md7csV3GzATIRanEi/view

@LudvikAdamec you can try it with the new version. If it works, please close this ticket.

**Comment by LudvikAdamec** [comment]
There is a problem with formatting differences between new and old stanice_tok.csv 

Old example:
"001","LG Raškov","Morava","50° 2' 27.440""","16° 54' 41.059"""

New example:
1,LG Raškov,Morava,"50° 2' 27.440""","16° 54' 41.059"""

**Comment by stampachradim** [comment]
Well, problem seems to be mainly in ID column. You should decide what is better solution:
1) Change format of old values to format of new values
2) Change format of new values to format of old values
I can do this if you want. however, what is better version?

**Comment by LudvikAdamec** [comment]
Please change format of new values to format of old values.

**Comment by LudvikAdamec** [comment]
Done
