### ISSUE TITLE
Import other properties from ALA

### ISSUE THREAD

**Issue by Darkless012** [gis4dis/poster#3]
<a href="https://github.com/jirik"><img src="https://avatars0.githubusercontent.com/u/2271850?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jirik](https://github.com/jirik)**
_Monday Oct 16, 2017 at 12:10 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/gis4dis/poster_obsolete/issues/8_

----

- wind speed
- wind direction
- solar energy

For only one station: [Brno, Hroznová](http://a.la-a.la/chart/data.php?probe=11359202&user=applet11359202&t1=1509941700&t2=1510546500)

https://en.wikipedia.org/wiki/Mean_of_circular_quantities

Suggestion:
- store wind speed and wind direction as wind vector (implemented as PostGIS `Point`)
- show it as combination of wind direction and wind speed

**Comment by jirik** [comment]
Implemented by https://github.com/gis4dis/poster/pull/20
Thanks to @LudvikAdamec
