### ISSUE TITLE
Incompatible celery package version

### ISSUE THREAD

**Issue by SLeitgeb** [gis4dis/poster#33]
During build, pip throws a warning:
"django-celery 3.2.2 has requirement celery<4.0,>=3.1.15, but you'll have celery 4.0.2 which is incompatible."

Doesn't seem to break anything though.

**Comment by jirik** [comment]
@Darkless012 If I understood correctly on Friday, this one is solved now, right? If so, please close this issue (and check also #11).

**Comment by Darkless012** [comment]
Correct
