### ISSUE TITLE
Add initial data scripts in django

### ISSUE THREAD

**Issue by Darkless012** [gis4dis/poster#5]
<a href="https://github.com/Darkless012"><img src="https://avatars2.githubusercontent.com/u/1187034?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Darkless012](https://github.com/Darkless012)**
_Friday Nov 24, 2017 at 11:12 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/gis4dis/poster_obsolete/issues/19_

----

There are few initial static data that should be present in DB. Find a way to import the data on init (ansible? django?)

**Comment by jirik** [comment]
obsolete
