### ISSUE TITLE
Gettimeseries - number of return values

### ISSUE THREAD

**Issue by LudvikAdamec** [gis4dis/poster#51]
I think there is a bug in the number of values returned from get_timeseries. The method returns probably one value more than I suppose there should be.

Example:

Result from get_timeseries:
range from:  2018-05-13 00:00:00
range to:  2018-05-30 23:00:00
value_frequency:  3600
len property_values:  432

There is a problem because we have assurance
   feature.property_values.length <=
(phenomenon_time_to::seconds - phenomenon_time_from::seconds) /
value_frequency
- I think method should in described example return 431 values.

**Comment by jirik** [comment]
Related part of specification: https://github.com/gis4dis/poster/wiki/Interface-between-MC-server-&-AD/_compare/d1c5ba70db40133cef5b879dee10ab60073c5e52...e9eed624eda13da971c0ff872eff41401842346b

**Comment by jirik** [comment]
So the problem is probably not in number of observations, but in range - it's shorter than it should be

**Comment by jirik** [comment]
Solved by #54
