### ISSUE TITLE
Add created_at, updated_at fields to common.Observation

### ISSUE THREAD

**Issue by Darkless012** [gis4dis/poster#7]
<a href="https://github.com/jirik"><img src="https://avatars0.githubusercontent.com/u/2271850?v=4" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jirik](https://github.com/jirik)**
_Monday Dec 11, 2017 at 17:11 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/gis4dis/poster_obsolete/issues/24_

----

Later consider also https://django-simple-history.readthedocs.io/en/latest/

**Comment by jirik** [comment]
auto_now, auto_now_add
