### ISSUE TITLE
GitHub dependency in Pipfile not loaded properly

### ISSUE THREAD

**Issue by SLeitgeb** [gis4dis/poster#98]
When adding a new package through pipenv from GitHub remote (e.g. pipenv install -e git+https://github.com/gis4dis/luminol.git#egg=luminol), the package is installed properly, but cannot be imported in docker container. It fails with the following:

poster-web              |   File "/code/apps/ad/anomaly_detection.py", line 4, in <module>
poster-web              |     from luminol.anomaly_detector import AnomalyDetector
poster-web              | ModuleNotFoundError: No module named 'luminol'

The issue can be tested on the branch "pipfile-dependencies".

**Comment by Darkless012** [comment]
Fix on local dev env, need to test on Flynn.
